# Define

# Main
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=true,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=true,north=false,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=true,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_wood
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_wood[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:stripped_smoldering_bamboo_fencegate_wood[east=false,north=false,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_wood