# Define

# Main
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=true,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=true,north=false,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=true,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_planks
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_slab[east=false,north=false,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_planks