attribute @s gstools:disease_effect_hunger base set 0
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=1..1,diseaseTime=1000..}] run attribute @s gstools:disease_effect_hunger base set 9
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=1000..2000}] run attribute @s gstools:disease_effect_hunger base set 17
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=2000..}] run attribute @s gstools:disease_effect_hunger base set 17
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=1000..2000}] run attribute @s gstools:disease_effect_hunger base set 25
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=2000..3000}] run attribute @s gstools:disease_effect_hunger base set 25
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=3000..}] run attribute @s gstools:disease_effect_hunger base set 25
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=1000..2000}] run attribute @s gstools:disease_effect_hunger base set 33
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=2000..3000}] run attribute @s gstools:disease_effect_hunger base set 33
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=3000..4000}] run attribute @s gstools:disease_effect_hunger base set 33
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=1..1,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=4000..}] run attribute @s gstools:disease_effect_hunger base set 33
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=1..1,diseaseTime=2000..}] run attribute @s gstools:disease_effect_hunger base set 10
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=2000..3000}] run attribute @s gstools:disease_effect_hunger base set 18
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=3000..}] run attribute @s gstools:disease_effect_hunger base set 18
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=2000..3000}] run attribute @s gstools:disease_effect_hunger base set 26
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=3000..4000}] run attribute @s gstools:disease_effect_hunger base set 26
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=4000..}] run attribute @s gstools:disease_effect_hunger base set 26
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=2000..3000}] run attribute @s gstools:disease_effect_hunger base set 34
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=3000..4000}] run attribute @s gstools:disease_effect_hunger base set 34
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=4000..5000}] run attribute @s gstools:disease_effect_hunger base set 34
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=2..2,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=5000..}] run attribute @s gstools:disease_effect_hunger base set 34
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=1..1,diseaseTime=3000..}] run attribute @s gstools:disease_effect_hunger base set 11
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=3000..4000}] run attribute @s gstools:disease_effect_hunger base set 19
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=4000..}] run attribute @s gstools:disease_effect_hunger base set 19
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=3000..4000}] run attribute @s gstools:disease_effect_hunger base set 27
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=4000..5000}] run attribute @s gstools:disease_effect_hunger base set 27
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=5000..}] run attribute @s gstools:disease_effect_hunger base set 27
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=3000..4000}] run attribute @s gstools:disease_effect_hunger base set 35
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=4000..5000}] run attribute @s gstools:disease_effect_hunger base set 35
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=5000..6000}] run attribute @s gstools:disease_effect_hunger base set 35
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=3..3,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=6000..}] run attribute @s gstools:disease_effect_hunger base set 35
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=1..1,diseaseTime=4000..}] run attribute @s gstools:disease_effect_hunger base set 12
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=4000..5000}] run attribute @s gstools:disease_effect_hunger base set 20
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=2..2,diseaseTime=5000..}] run attribute @s gstools:disease_effect_hunger base set 20
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=4000..5000}] run attribute @s gstools:disease_effect_hunger base set 28
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=5000..6000}] run attribute @s gstools:disease_effect_hunger base set 28
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=3..3,diseaseTime=6000..}] run attribute @s gstools:disease_effect_hunger base set 28
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=4000..5000}] run attribute @s gstools:disease_effect_hunger base set 36
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=5000..6000}] run attribute @s gstools:disease_effect_hunger base set 36
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=6000..7000}] run attribute @s gstools:disease_effect_hunger base set 36
execute if entity @s[scores={hasDiseaseBoolean=1..2,hung_minact_tier=4..,hung_boolean=1..1,hung_max_tier=4..,diseaseTime=7000..}] run attribute @s gstools:disease_effect_hunger base set 36