# Define

# Main
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=true,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=true,north=false,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=true,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=true,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=true,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=true,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=true,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=false,west=true,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=true] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=false,west=true,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=false,west=false,waterlogged=true] replace burnt:smoldering_bamboo_fencegate_fence
execute if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[east=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[north=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[south=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[west=false] if block ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_fence[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:smoldering_bamboo_fencegate_slab[east=false,north=false,south=false,west=false,waterlogged=false] replace burnt:smoldering_bamboo_fencegate_fence