# Define

# Main
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=true,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=true,north=false,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=true,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=true,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=true,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=true,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=true,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=false,west=true,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=true] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=false,west=true,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=false,west=false,waterlogged=true] replace burnt:burnt_bamboo_fencegate_stairs
execute if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[east=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[north=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[south=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[west=false] if block ~ ~-1 ~ burnt:burnt_bamboo_fencegate_stairs[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:burnt_bamboo_fencegate_planks[east=false,north=false,south=false,west=false,waterlogged=false] replace burnt:burnt_bamboo_fencegate_stairs