# Define

# Main
# <node:no_compile_mode>
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n38/burnt_geyser_shoot
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n110/burnt_smoldering_cactus
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n258/burnt_burnt_ladder
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_burnt_soul_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_burnt_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_smoldering_cherry_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_blast_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_smoldering_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_soul_spruce_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_soul_mangrove_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_soul_acacia_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_smoldering_acacia_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_smoldering_spruce_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_soul_cherry_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n300/burnt_smoldering_mangrove_leaves
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n96/burnt_smoldering_carpet
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n96/burnt_burnt_carpet
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n96/burnt_smoldering_moss_carpet
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n29/burnt_burnt_sugar_cane
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n407/burnt_recovering_grass
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n408/burnt_smoldering_grass_start
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n409/burnt_burnt_spruce_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n410/burnt_smoldering_high_grass
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n411/burnt_smoldering_potatoes
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n414/burnt_blaze_barrel
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n415/burnt_burnt_grass
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n417/burnt_smoldering_wheat
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n421/burnt_smoldering_beetroot
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n422/burnt_smoldering_cave_vines_plant
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n423/burnt_burnt_farmland
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n424/burnt_burnt_acacia_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n426/burnt_burnt_cave_vines_plant
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n427/burnt_burnt_scaffolding
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n429/burnt_smoldering_grass
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n431/burnt_burnt_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n432/burnt_geyser_water
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n433/burnt_burnt_campfire
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n436/burnt_burnt_vine
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n438/burnt_smoldering_mangrove_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n440/burnt_smoldering_azalea
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n441/burnt_soul_wart
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n442/burnt_smoldering_soul_wart
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n443/burnt_tall_grass_burnt
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n444/burnt_smoldering_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n445/burnt_smoldering_coal
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n446/burnt_smoldering_campfire
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n448/burnt_smoldering_acacia_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n458/burnt_burnt_acacia_trapdoor
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n459/burnt_burnt_ivy
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n460/burnt_soul_fire_10
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n461/burnt_smoldering_fencegate
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n462/burnt_fire_barrel_active
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n463/burnt_burnt_azalea
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n465/burnt_burnt_mangrove_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n466/burnt_smoldering_crops
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n468/burnt_burnt_cave_vines
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n470/burnt_firestarter
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n471/burnt_smoldering_acacia_trapdoor
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n472/burnt_burning_cave_vines_plant
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n473/burnt_smoldering_cave_vines
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n474/burnt_blaze_barrel_active
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n475/burnt_smoldering_spruce_door
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n477/burnt_fire_barrel
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n479/burnt_burnt_barrel
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n480/burnt_burnt_high_grass
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n481/burnt_smoldering_carrots
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n482/burnt_burnt_spruce_trapdoor
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n483/burnt_grave_lean
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n484/burnt_burnt_crops
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n485/burnt_burnt_button
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n486/burnt_burnt_trapdoor
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n487/burnt_burnt_fencegate
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n488/burnt_burnt_mangrove_trapdoor
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n74/burnt_sooty_andesite
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n78/burnt_sooty_stone
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n86/burnt_flaming_tar
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n98/burnt_black_ice
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n164/burnt_sooty_cherry_slab
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n200/burnt_sooty_cherry_stairs
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n202/burnt_sooty_cherry_fence
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n211/burnt_sooty_mossy_stone_bricks
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n216/burnt_sooty_mossy_cobblestone_slab
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n413/burnt_grave_back
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n418/burnt_grave_twist
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n425/burnt_grave
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n439/burnt_shale
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n251/burnt_sooty_dark_oak_stairs
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n254/burnt_liquid_magma
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n263/burnt_smoldering_mangrove_roots
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n266/burnt_sooty_andesite_stairs
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n269/burnt_sooty_granite_stairs
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n272/burnt_sooty_diorite_stairs
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n71/burnt_smoldering_wool
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n71/burnt_burnt_wool
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n26/burnt_sooty_mossy_cobblestone
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n45/burnt_burnt_grassy_earthen_clay
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n47/burnt_sooty_birch_planks
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n62/burnt_burnt_dirt
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n95/burnt_semi_burnt_dirt
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n167/burnt_burnt_cherry_trapdoor
execute if blocks ~ ~-1 ~ ~ ~-1 ~ 0 0 0 all run function blockdecay:compat/burnt/layer_0/n447/burnt_fragile_magma
# <node:no_compile_mode/>