# Define

# Main
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=true,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=true,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=true,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=true,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=false,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=false,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=false,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=true,south=false,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=true,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=true,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=true,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=true,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=false,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=false,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=false,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=true,north=false,south=false,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=true,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=true,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=true,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=true,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=false,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=false,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=false,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=true,south=false,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=true,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=true,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=true,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=true,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=false,west=true,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=true] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=false,west=true,waterlogged=false] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=true] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=false,west=false,waterlogged=true] replace burnt:blaze_barrel_blast_bars
execute if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[east=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[north=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[south=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[west=false] if block ~ ~-1 ~ burnt:blaze_barrel_blast_bars[waterlogged=false] run fill ~ ~-1 ~ ~ ~-1 ~ burnt:oxidized_blaze_barrel_blast_bars[east=false,north=false,south=false,west=false,waterlogged=false] replace burnt:blaze_barrel_blast_bars